"""Constants for Toyota LATAM."""

DOMAIN = "toyota_latam"

CONF_ACTIVE_INTERVAL = "active_interval"
CONF_PARKED_INTERVAL = "parked_interval"
CONF_RESOLVE_ADDRESS = "resolve_address"

DEFAULT_ACTIVE_INTERVAL = 30
DEFAULT_PARKED_INTERVAL = 300
DEFAULT_RESOLVE_ADDRESS = True
MIN_INTERVAL = 15
MAX_INTERVAL = 3600

GARAGE_REFRESH = 6 * 3600
GEOFENCE_REFRESH = 600
TRIPS_REFRESH = 15 * 60
MAX_STALE_FAILURES = 3
MAX_BACKOFF = 15 * 60
GEOCODE_MIN_MOVE_M = 50
SLOW_REFRESH = 3600
DIAGNOSTICS_REFRESH = 900
ALERTS_REFRESH = 600
